######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Laurens de Groot"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

######################## voorpagina ####################

voorpagina_layout_schema = [
  [
    "3-poster-foto",
  ],
  [
    "1-fotokaart-blog",
    "1-fotokaart-blog",
    "1-lijst-agenda"
  ],
  [
    "2-poster-blog",
    "1-fotokaart-blog"
  ],
  [
    "1-lijst-column",
    "1-kaart-blog",
    "1-fotokaart-blog",
  ],
  [
    "3-fotokaart-blog"
  ],
  [
    "1-fotokaart-blog",
    "1-kasjmier-blog",
    "1-fotokaart-blog"
  ],
  [
    "1-dubbelspaanswitkaart-blog",
    "2-poster-foto"
  ],
  [
    "1-fotokaart-blog",
    "1-fotokaart-blog",
    "1-mortalkaart-blog"
  ]
]

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "Blog."
URL = "blog"
weight = 2

[[menu.main]]
name = "Pers."
URL = "pers/pers"
weight = 3

[[menu.main]]
name = "Contact."
URL = "contact"
weight = 4


#################### default parameters ################################
[params]
logo = "images/logo.svg"
home = "Home"
# Meta data
description = "This is meta description"
author = "Laurens de Groot"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "+31 6 31 76 99 37"
email = "info@manmetkoffer.nl"
location = "Zoetermeer"
# copyright
copyright = "@2019 Laurens de Groot - Alle rechten voorbehouden"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = false

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/laurens.degroot.79"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/degrootlaurens"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/laurens.degroot/"

[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/user/manmetkoffer"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/laurens-de-groot-55771112/?locale=nl_NL"
