hugover = "0.62.1"

[[serve]]
key = "default"
config = "config.toml"

[[build]]
key = "default"
config = "config.toml"

[[collections]]
key = "blog"
title = "Blogs"
folder = "content/blog/"
extension = "md"
dataformat = "yaml"
itemtitle = "Blogitem"

  [[collections.fields]]
  key = "title"
  title = "Titel"
  type = "string"

#  [[collections.fields]]
#  key = "weight"
#  title = "Sorteerprioriteit"
#  type = "number"

  [[collections.fields]]
  key = "pubdate"
  title = "Publicatiedatum"
  type = "date"
  default = "now"

  [[collections.fields]]
  key = "categories"
  title = "Categorieën"
  type = "chips"

  [[collections.fields]]
  key = "draft"
  title = "Concept"
  type = "boolean"
  tip = "Wordt niet gepubliceerd."

  [[collections.fields]]
  title = "Headerbeelden"
  key = "bundle-manager"
  type = "bundle-manager"
  path = "headerimgs"
  extensions = [
    "png",
    "jpg",
    "gif"
  ]

  [[collections.fields.fields]]
  key = "thumb"
  title = "Thumbnail"
  type = "bundle-image-thumbnail"

  [[collections.fields]]
  key = "mainContent"
  title = "Content"
  type = "markdown"


[[collections]]
key = "fotos"
title = "Foto's"
folder = "content/foto/"
extension = "md"
dataformat = "yaml"
itemtitle = "Foto's"

#  [[collections.fields]]
#  key = "weight"
#  title = "Sorteerprioriteit"
#  type = "number"

  [[collections.fields]]
  title = "Headerbeelden"
  key = "bundle-manager"
  type = "bundle-manager"
  path = "headerimgs"
  extensions = [
    "png",
    "jpg",
    "gif"
  ]

  [[collections.fields.fields]]
  key = "thumb"
  title = "Thumbnail"
  type = "bundle-image-thumbnail"

#  [[collections.fields]]
#  key = "mainContent"
#  title = "Content"
#  type = "markdown"

[[singles]]
key = "contactpagina"
title = "Pagina: Contact"
file = "content/contact/_index.md"
dataformat = "yaml"

  [[singles.fields]]
  key = "title"
  title = "Paginatitel"
  type = "string"

  [[singles.fields]]
  key = "description"
  title = "Meta: description"
  type = "string"
  multiLine = true

  [[singles.fields]]
  key = "keywords"
  title = "Meta: keywords"
  type = "string"
  multiLine = true

  [[singles.fields]]
  key = "mainContent"
  title = "Content"
  type = "markdown"

[[singles]]
key = "perspagina"
title = "Pagina: Pers"
file = "content/pers/pers.md"
dataformat = "yaml"

  [[singles.fields]]
  key = "title"
  title = "Paginatitel"
  type = "string"

  [[singles.fields]]
  key = "description"
  title = "Meta: description"
  type = "string"
  multiLine = true

  [[singles.fields]]
  key = "keywords"
  title = "Meta: keywords"
  type = "string"
  multiLine = true


  [[singles.fields]]
  title = "Headerbeelden"
  key = "bundle-manager"
  type = "bundle-manager"
  path = "headerimgs"
  extensions = [
    "png",
    "jpg",
    "gif"
  ]

  [[singles.fields]]
  key = "mainContent"
  title = "Content"
  type = "markdown"

[[singles]]
key = "agenda"
title = "Agenda"
file = "data/agenda.yml"

  [[singles.fields]]
  key = "data"
  title = "Data"
  type = "accordion"

    [[singles.fields.fields]]
    key = "datum"
    title = "Datum"
    type = "string"
    arrayTitle = true

    [[singles.fields.fields]]
    key = "voorstelling"
    title = "Voorstelling"
    type = "string"
    arrayTitle = true

    [[singles.fields.fields]]
    key = "locatie"
    title = "Locatie"
    type = "string"

  [[singles.fields]]
  key = "accordion-section-info"
  type = "info"
  theme = "black-bare"
  content = "Voeg hier de agendaitems toe"

[[singles]]
key = "layout"
title = "Voorpagina Indeling"
file = "data/voorpaginalayout.yaml"

  [[singles.fields]]
  key = "rijen"
  title = "Rijen"
  type = "accordion"

    [[singles.fields.fields]]
    key = "naam"
    title = "Rijnaam"
    type = "string"
    tip = "Geef een naam zodat je de rij kunt hernennen"
    arrayTitle = true

    [[singles.fields.fields]]
    key = "verborgen"
    title = "Verborgen"
    type = "boolean"

    [[singles.fields.fields]]
    key = "kolommen"
    title = "Kolommen"
    type = "accordion"

      [[singles.fields.fields.fields]]
      key = "aantalkol"
      title = "Breedte in kolommen"
      type = "select"

        [[singles.fields.fields.fields.options]]
        text = "1"
        value = "1"

        [[singles.fields.fields.fields.options]]
        text = "2"
        value = "2"

        [[singles.fields.fields.fields.options]]
        text = "3"
        value = "3"

      [[singles.fields.fields.fields]]
      key = "widget"
      title = "Widget"
      type = "select"
      arrayTitle = true

        [[singles.fields.fields.fields.options]]
        text = "foto"
        value = "poster"

        [[singles.fields.fields.fields.options]]
        text = "video"
        value = "video"

        [[singles.fields.fields.fields.options]]
        text = "foto en tekst"
        value = "fototekst"

        [[singles.fields.fields.fields.options]]
        text = "agendalijst met laatste 4 items"
        value = "lijstagenda"

        [[singles.fields.fields.fields.options]]
        text = "bloglijst met laatste items"
        value = "lijstblog"

      [[singles.fields.fields.fields]]
      key = "code"
      title = "Code"
      type = "string"
      tip = "Geef de unieke code van het blogitem, de foto, of de youtube-video"

[[singles]]
key = "mainConfig"
title = "Website instellingen"
file = "config.toml"

  [[singles.fields]]
  key = "title"
  title = "Websitetitel"
  type = "string"

  [[singles.fields]]
  key = "email"
  title = "Emailadres"
  type = "string"

  [[singles.fields]]
  key = "mobile"
  title = "Telefoornummer"
  type = "string"

  [[singles.fields]]
  key = "location"
  title = "Locatie"
  type = "string"

  [[singles.fields]]
  key = "copyright"
  title = "Copyright tekst"
  type = "string"

  [[singles.fields]]
  key = "baseURL"
  title = "Base URL"
  type = "readonly"

  [[singles.fields]]
  key = "theme"
  title = "Theme"
  type = "readonly"
