hugover = "0.62.1"

[[serve]]
key = "default"
config = "config.toml"

[[build]]
key = "default"
config = "config.toml"

[[collections]]
key = "blog"
title = "Blogs"
folder = "content/blog/"
extension = "md"
dataformat = "yaml"
itemtitle = "Post"

  [[collections.fields]]
  key = "title"
  title = "Titel"
  type = "string"

  [[collections.fields]]
  key = "type"
  title = "Type"
  type = "select"

  [[collections.fields.options]]
  text = "Artikel"
  value = "blog"

  [[collections.fields.options]]
  text = "Foto"
  value = "foto"

  [[collections.fields]]
  key = "image"
  title = "Afbeelding"
  type = "string"

  [[collections.fields]]
  key = "pubdate"
  title = "Publicatiedatum"
  type = "date"
  default = "now"

  [[collections.fields]]
  key = "draft"
  title = "Concept"
  type = "boolean"
  tip = "Wordt niet gepubliceerd."

  [[collections.fields]]
  key = "bundle-manager"
  type = "bundle-manager"
  path = "imgs"
  extensions = [
    "png",
    "jpg",
    "gif"
  ]

    [[collections.fields.fields]]
    key = "title"
    title = "Title"
    type = "string"

    [[collections.fields.fields]]
    key = "description"
    title = "Description"
    type = "string"
    multiLine = true

  [[collections.fields]]
  key = "mainContent"
  title = "Content"
  type = "markdown"

[[singles]]
key = "contactpagina"
title = "Pagina: Contact"
file = "content/contact/_index.md"
dataformat = "yaml"

  [[singles.fields]]
  key = "title"
  title = "Paginatitel"
  type = "string"

  [[singles.fields]]
  key = "description"
  title = "Meta: description"
  type = "string"
  multiLine = true

  [[singles.fields]]
  key = "keywords"
  title = "Meta: keywords"
  type = "string"
  multiLine = true

  [[singles.fields]]
  key = "mainContent"
  title = "Content"
  type = "markdown"

[[singles]]
key = "perspagina"
title = "Pagina: Pers"
file = "content/pers/pers.md"
dataformat = "yaml"

  [[singles.fields]]
  key = "title"
  title = "Paginatitel"
  type = "string"

  [[singles.fields]]
  key = "description"
  title = "Meta: description"
  type = "string"
  multiLine = true

  [[singles.fields]]
  key = "keywords"
  title = "Meta: keywords"
  type = "string"
  multiLine = true

  [[singles.fields]]
  key = "mainContent"
  title = "Content"
  type = "markdown"

[[singles]]
key = "agenda"
title = "Agenda"
file = "data/agenda2.yml"

  [[singles.fields]]
  key = "data"
  title = "Data"
  type = "accordion"

    [[singles.fields.fields]]
    key = "datum"
    title = "Datum"
    type = "string"
    arrayTitle = true

    [[singles.fields.fields]]
    key = "voorstelling"
    title = "Voorstelling"
    type = "string"
    arrayTitle = true

    [[singles.fields.fields]]
    key = "locatie"
    title = "Locatie"
    type = "string"

  [[singles.fields]]
  key = "accordion-section-info"
  type = "info"
  theme = "black-bare"
  content = "Voeg hier de agendaitems toe"

[[singles]]
key = "mainConfig"
title = "Website instellingen"
file = "config.toml"

  [[singles.fields]]
  key = "title"
  title = "Site Titel"
  type = "string"

  [[singles.fields]]
  key = "baseURL"
  title = "Base URL"
  type = "readonly"

  [[singles.fields]]
  key = "theme"
  title = "Theme"
  type = "readonly"
